### ISSUE TITLE
carbon-sdk support hdfs ?

### ISSUE THREAD

**Issue by BestP2P** [apache/carbondata#4144]
Writing carbondata files from other application which does not use Spark，it is support hdfs configure? how can i write the carbondata to hdfs system?

**Comment by nihal0107** [comment]
Hi,
   Yes, carbon-SDK supports hdfs configuration.
   When building a carbon writer, you can use API named `withHadoopConf(Configuration conf)` to pass the detailed configuration of HDFS. You can find an example for S3 given in SDKS3Example.java. In similar way you can use for HDFS.

**Comment by BestP2P** [comment]
thank you very much from china!
