### ISSUE TITLE
How to build successful of presto 333 version ？

### ISSUE THREAD

**Issue by czy006** [apache/carbondata#4184]
@ajantha-bhat hello,I always build fail for your presto version about 333,I don't know what's problem,it must be use jdk11 to build it ? My mvn build command is my build command is mvn -DskipTests -Pspark-2.4 -Pprestosql -Dspark.version=2.4.5 -Dhadoop.version=2.7.7 -Dhive.version=3.1.0 ，but it say error is： has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0 . This is mean not support jdk8

**Comment by ajantha-bhat** [comment]
@czy006 : Hi, can you use spark2.3 profile instead of 2.4 ? 2.4 brings hadoop3 dependencies which doesn't work well with presto333.  
Also remove Dhadoop, Dhive version and try
